repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: check-docstring-first
      - id: check-added-large-files
      - id: check-json

  - repo: https://github.com/asottile/reorder-python-imports
    hooks:
      - id: reorder-python-imports


  - repo: https://github.com/asottile/yesqa
    hooks:
      - id: yesqa
        additional_dependencies: [types-all]

  - repo: https://github.com/adrienverge/yamllint.git
    hooks:
      - id: yamllint
        args: ['-d {extends: relaxed, rules: {line-length: disable}}', '-s']

  - repo: https://github.com/psf/black
    hooks:
      - id: black


  - repo: https://github.com/pre-commit/mirrors-mypy
    hooks:
      - id: mypy
        entry: sh -c 'PYTHONPATH="${PWD}/src" TYPE_CHECKING=1 exec mypy "$@"' --
        additional_dependencies: [types-all]

  - repo: https://github.com/pre-commit/mirrors-pylint
    hooks:
      - id: pylint


  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --sequence, '4', --offset, '2', --preserve-quotes]

  - repo: https://github.com/asottile/add-trailing-comma
    hooks:
      - id: add-trailing-comma


  - repo: https://github.com/asottile/pyupgrade
    hooks:
      - id: pyupgrade


  - repo: https://github.com/hadialqattan/pycln
    hooks:
      - id: pycln


